name: mercave
description: Merca Ve - Aplicación de Compra de Mercado
version: 1.1.3+16

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ^1.20.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  woocommerce_api: ^0.0.8
  font_awesome_flutter: ^8.5.0
  carousel_slider: ^1.3.1
  sqflite: ^1.1.7+3
  path_provider: ^1.5.1
  flutter_spinkit: ^4.1.1
  intl: ">=0.14.0"
  url_launcher: ^5.2.5
  flutter_facebook_login: ^3.0.0
  photo_view: ^0.9.1
  badges: ^1.1.0
  flutter_webview_plugin: ^0.3.11
  path: ^1.6.4
  cached_network_image: ^2.2.0+1
  package_info: ^0.4.0+18
  share: ">=0.6.4+5 <2.0.0"
  firebase_messaging: ^7.0.3
  sign_in_with_apple: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  splashscreen:

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
