name: mercave
description: Merca Ve - Aplicación de Compra de Mercado
version: 1.1.3+16

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  http: ^0.13.3
  woocommerce_api: ^0.1.0
  font_awesome_flutter: ^9.2.0
  carousel_slider: ^4.0.0
  sqflite: ^2.0.0+4
  path_provider: ^2.0.4
  flutter_spinkit: ^5.1.0
  intl: ">=0.14.0"
  url_launcher: ^6.0.10
  #flutter_facebook_login: ^3.0.0
  photo_view: ^0.13.0
  badges: ^2.0.1
  flutter_webview_plugin: ^0.4.0
  path: ^1.6.4
  cached_network_image: ^3.1.0+1
  package_info: ^2.0.2
  share: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  splashscreen:

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
